// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9daDw7g-yGVmzWJkPp24OwiwH_HO02qI',
    appId: '1:349405037583:web:8ba7090335e51a0a54cf7a',
    messagingSenderId: '349405037583',
    projectId: 'project-2910725798392866741',
    authDomain: 'project-2910725798392866741.firebaseapp.com',
    storageBucket: 'project-2910725798392866741.appspot.com',
    measurementId: 'G-NJ7TN2HL1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4dkZMGXIR-qWsrOviVL-txuOgj3EfrCE',
    appId: '1:349405037583:android:c87791d74ea1cdfb54cf7a',
    messagingSenderId: '349405037583',
    projectId: 'project-2910725798392866741',
    storageBucket: 'project-2910725798392866741.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp-hrcQaOVjnHRT_So8RmBccqKsf4txzA',
    appId: '1:349405037583:ios:0551cb7d4e9e05e954cf7a',
    messagingSenderId: '349405037583',
    projectId: 'project-2910725798392866741',
    storageBucket: 'project-2910725798392866741.appspot.com',
    iosClientId: '349405037583-741thrva0je1rg0i7ic1se7lg4smq95m.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloWorld',
  );
}
